### ISSUE TITLE
Input and Output Formats don't support deprecated APIs

### ISSUE THREAD

**Issue by sritchie** [infochimps-labs/wonderdog#1]
Hey all,

I'm looking to leverage your work here to create a Cascading tap into ElasticSearch. The problem is that Cascading still uses the JobConf parameter, which has to use input and output formats that extend the old `org.apache.hadoop.mapred.OutputFormat` vs  the newer `org.apache.hadoop.mapreduce.OutputFormat`.

Would you guys mind if I fork wonderdog and implement these deprecated APIs? Alternatively, if you don't want them in your project I can do this separately in my tap project. Just wanted to check in and see what you thought was the best way to move forward.

Cheers,
Sam Ritchie
Twitter Inc

**Comment by kornypoet** [comment]
@sritchie Sorry for the (very) delayed response. Go ahead and fork if you already have not.

**Comment by sritchie** [comment]
Thanks @kornypoet, will do.
