### ISSUE TITLE
Wonderdog doesn't work with 0.19.0, as the APIs have changed

### ISSUE THREAD

**Issue by rjurney** [infochimps-labs/wonderdog#3]

**Comment by kornypoet** [comment]
@rjurney Can you provide any assistance with reconciling to the new version?

**Comment by rjurney** [comment]
Yes, when I have the brain power.  Java makes me cry.

**Comment by kornypoet** [comment]
It appears @joearasin has made this possible.
See commit: 17784eb90cf578c1ed44e5cdf0121c3ce1529620

**Comment by joearasin** [comment]
I think 0.19 is different from 0.18.7, but don't quote me on it.

**Comment by kornypoet** [comment]
@joearasin is right, 0.19.0.RC1 makes another breaking change to the API. It's minor, and we are still using 18.7, so I am not going to patch Wonderdog right away. @rjurney if you look at @joearasin's commit you should see the relevant changes, and this link has the new class names: http://www.elasticsearch.org/download/2012/02/07/0.19.0.RC1.html

I will (soon) create versioned branches of Wonderdog to match Elasticsearch's versions, and that will also address the issue.

**Comment by mrflip** [comment]
Closed by #8, I believe
